# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 14:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='date_createG',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='goal',
            name='doneDateG',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='dueDateG',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='subtask',
            name='date_createS',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='subtask',
            name='doneDateS',
            field=models.DateTimeField(null=True),
        ),
    ]
