# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20170902_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='task_desc',
        ),
    ]
